use std::path::PathBuf;

fn main() {
    // Directory where the tree-sitter grammar for Lexon is located
    // Assume it is at ../tree-sitter-lexon/src/
    // tree-sitter generate normally places parser.c and scanner.c (if present) in a 'src'
    // directory inside the grammar directory.
    let grammar_dir = PathBuf::from("..").join("tree-sitter-lexon").join("src");

    // Main parser file generated by tree-sitter
    let parser_file = grammar_dir.join("parser.c");

    // Scanner file, if the grammar uses it (optional)
    // Some grammars do not need an external scanner.c
    let scanner_file = grammar_dir.join("scanner.c");

    println!("cargo:rerun-if-changed={}", parser_file.display());
    if scanner_file.exists() {
        println!("cargo:rerun-if-changed={}", scanner_file.display());
    }
    println!("cargo:rerun-if-changed=build.rs");

    let mut build = cc::Build::new();
    build.file(&parser_file).include(&grammar_dir); // Include directory so parser.c finds tree_sitter/parser.h
                                                    // if the grammar is structured like this or scanner.c needs parser.h

    // If scanner.c exists, compile it too.
    // Ensure scanner.c does not define a main() function.
    if scanner_file.exists() {
        build.file(&scanner_file);
        println!("Compiling scanner: {}", scanner_file.display());
    } else {
        println!(
            "Scanner file not found or not used: {}",
            scanner_file.display()
        );
    }

    // Avoid common warnings in C code generated by tree-sitter
    build.warnings(false); // Or configure specific flags like .flag("-Wno-unused-parameter")

    // Compile C code for the parser
    // The static library will be named `lib<crate_name>.a` (e.g., liblexc.a); Cargo handles linking.
    build.compile("tree_sitter_lexon_parser"); // Intermediate lib name, e.g., libtree_sitter_lexon_parser.a

    println!("Successfully configured and compiled tree-sitter Lexon parser.");
}
